In [9]:
import datetime

In [11]:
datetime.datetime(1970, 1, 1).strftime('%Y-%d-%B')

'1970-01-January'

In [2]:
import numpy as np

In [5]:
5 / (2*np.bincount(np.array([1,0,1,1,0])))

array([1.25      , 0.83333333])

In [ ]:
0-2,1-3

In [6]:
2/3

0.6666666666666666

In [44]:
a = np.ones(int(1e5))

In [9]:
0.01*1e5

1000.0

In [45]:
a[0:10000] = 0

In [46]:
a

array([0., 0., 0., ..., 1., 1., 1.])

In [47]:
np.bincount(a.astype(int))

array([10000, 90000])

In [54]:
(1e5 / (2*np.bincount(a.astype(int))))

array([5.        , 0.55555556])

In [21]:
from sklearn.utils.class_weight import compute_sample_weight

In [30]:
b = compute_sample_weight({0:9,1:1},a)

In [34]:
import pandas as pd

In [39]:
pd.Series(a).value_counts()

0.0    90000
1.0    10000
dtype: int64

In [38]:
pd.Series(b).value_counts()

9.0    90000
1.0    10000
dtype: int64

In [31]:
np.bincount(b.astype(int))

array([    0, 10000,     0,     0,     0,     0,     0,     0,     0,
       90000])

In [32]:
np.unique(b.astype(int))

array([1, 9])

In [40]:
scale_pos_weights = 90000/10000

In [49]:
x = 0

In [62]:
import math

In [55]:
x1 = 65
x2 = 60

In [66]:
sd = np.std(np.array([x1, x2]))

In [68]:
((x1-x2)**2)/sd

10.0

In [ ]:
f

In [69]:
f = np.exp(10)

In [52]:
gini = np.piecewise(f, [f < 0, x >= 0], [-1, 1])

True